# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# config/database.yml
development:
  adapter: postgresql
  encoding: unicode
  database: lab_11_development
  pool: 5
  username: alya
  password: 89391207
  host: localhost

test:
  <<: *default
  database: lab_11_test


production:
  <<: *default
  database: lab_11_production
  username: lab_11
  password: <%= ENV["LAB_11_DATABASE_PASSWORD"] %>
